Repository ThatConference/that-website, pull requests merged in 2019-10, with the labels that each got.

#36 Updated copy on call for speakers header bar message
  components/Header/MessageBar.js
Labels: enhancement

#42 website sample env
  .env.sample
Labels: enhancement

#44 Added Erin Gemoll to Crew. Carrie's last name case changed.
  components/HomePage/MeetCampers.js
Labels: bug, enhancement

#45 Remove about, contact, update meta
  components/Footer/MobileFooter.js
  components/Footer/PageFooter.js
  components/Footer/index.js
  components/Meta.js
  components/Nav/index.js
  pages/about.js
  pages/contact.js
  pages/index.js
  utilities/index.js
  utilities/siteInfo.js
Labels: enhancement

#49 Added Work in Progress landing page
  pages/workinprogress.js
Labels: enhancement

#63 resized and compressed images
  pages/wi/index.js
  public/images/battle_bots.jpg
  public/images/bear_with_drone.png
  public/images/bear_with_megaphone.png
  public/images/clark_stage.jpg
  public/images/keynote.jpg
  public/images/maker_space.jpg
  public/images/mess-hall.jpg
  public/images/mess_hall.jpg
  public/images/mess_hall.png
  public/images/octopus_with_flag.png
  public/images/robot.png
  public/images/sasquatch_close_up.png
  public/images/sasquatch_kayaking.png
  public/images/sasquatch_with_badge.png
  public/images/what_to_expect_200_speakers.png
  public/images/what_to_expect_4_days.png
  public/images/what_to_expect_families_welcome.png
  public/images/what_to_expect_hands_on_learning.png
  public/images/what_to_expect_industry_leaders.png
  public/images/what_to_expect_professional_networking.png
Labels: ready for review

#64 #35 fixed - homepage arrow icons now have centered arrowheads
  components/HomePage/Testimonials.js
  utilities/svgs.js
Labels: bug, ready for review
