Repository ThatConference/that-website, pull requests merged in 2019-12, with the labels that each got.

#94 Add ability to render markdown; includes copyright page as first example
  markdown/copyright.md
  next.config.js
  package-lock.json
  package.json
  pages/wi/[markdown].js
Labels: ready for review

#104 add contributing with markdown detail
  CONTRIBUTING.MD
Labels: ready for review

#126 started adding the auth
  .env.build.sample
  .vscode/settings.json
  lib/auth0.js
  lib/user.js
  next.config.js
  now.json
  package-lock.json
  package.json
  pages/_document.js
  pages/api/callback.js
  pages/api/login.js
  pages/api/logout.js
  pages/api/me.js
  pages/authTest.js
Labels: enhancement

#127 fixes broken faq link
  components/HomePage/LearnMore.js
Labels: bug

#128 adds Tidio integration
  pages/_document.js
Labels: enhancement

#129 enables ac tracking and email signup modal
  pages/_document.js
  pages/wi/index.js
Labels: enhancement

#144 package bumps, rendering changes and schema updates
  lib/sentry.js
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/wi/[markdown].js
  pages/wi/index.js
  pages/wi/partner/[slug].js
  pages/wi/partners.js
  pages/wi/plan-your-trip.js
Labels: enhancement

#165 Copy editing of Previous Talks on Call for Counselor's page
  components/CallForCounselors/TalkIdeas.js
Labels: enhancement

#167 Updated copy on several Call for Counselor pages.
  components/CallForCounselors/Perks.js
  components/CounselorAgreement/Commitments.js
  components/CounselorAgreement/WhatsProvided.js
  components/CounselorSelectionProcess/Bottom.js
  components/CounselorSelectionProcess/TheProcess.js
Labels: enhancement

#163 Use UTC dates when rendering the Key Dates section
  components/CallForCounselors/Process.js
Labels: bug

#168 enables oauth for api calls
  .env.build.sample
  .env.sample
  .vscode/settings.json
  lib/auth0.js
  lib/initApollo.js
  lib/withApolloClient.js
  next.config.js
  now.json
  package-lock.json
  package.json
  pages/api/callback.js
  pages/api/login.js
  pages/api/logout.js
  pages/api/me.js
Labels: enhancement

#176 only grabbing session when in ssr mode
  lib/withApolloClient.js
Labels: bug

#164 Copy edits for the "Format and Application Process" section.
  components/CallForCounselors/Process.js
Labels: enhancement

#178 Disable the eslint rule to warn on unescaped HTML entities
  .eslintrc.json
Labels: enhancement

#161 Link Button Hover Styles Issue #134
  components/CallForCounselors/Header.js
  components/CallForCounselors/Perks.js
  components/CallForCounselors/Process.js
  components/CallForCounselors/TalkIdeas.js
  components/CounselorSelectionProcess/Bottom.js
  components/CounselorStart/Header.js
  components/HomePage/Hero.js
  components/HomePage/LearnMore.js
  components/HomePage/MeetCampers.js
  components/HomePage/SpeakerHighlight.js
  components/HomePage/SponsorHighlight.js
  components/HomePage/Timeline.js
  components/PartnerDetail/HeroSection.js
  components/shared/LinkButton.js
  pages/_error.js
  pages/wi/become-a-partner.js
  pages/wi/contact.js
  pages/wi/partners.js
  pages/wi/plan-your-trip.js
Labels: enhancement

#180 Removed HTML entities from the Call for Counselors area.
  components/CallForCounselors/Perks.js
  components/CallForCounselors/Process.js
  components/CounselorAgreement/Acknowledgment.js
  components/CounselorAgreement/WhatsProvided.js
  components/CounselorStart/Header.js
Labels: enhancement

#179 link up call for counselors and open to main site
  components/CallForCounselors/Header.js
  components/CallForCounselors/Perks.js
  components/CallForCounselors/Process.js
  components/CallForCounselors/SummerCamp.js
  components/CounselorSelectionProcess/Header.js
  components/CounselorSelectionProcess/TheProcess.js
  components/Header/MessageBar.js
  components/Header/NavItem.js
  components/HomePage/Hero.js
  components/shared/ContentSection.js
  pages/wi/call-for-counselors.js
  pages/wi/counselor-selection-process.js
  styles/globalStyle.js
Labels: ready for review
