Repository ThatConference/that-website, pull requests merged in 2020-02, with the labels that each got.

#345 Partner goodness
  components/Header/MemberNav.js
  components/Header/Nav.js
  components/Header/index.js
  components/Page.js
  components/PartnerDetail/AboutGoalsSection.js
  components/PartnerDetail/HeroSection.js
  components/PartnerDetail/MainLogoSection.js
  components/PartnerDetail/PartnerDetailSubHeading.js
  components/PartnerDetail/PresentationsJobsSection.js
  components/layouts/default.js
  components/layouts/layeredHeader.js
  components/shared/Icon.js
  pages/_app.js
  pages/partner/[slug].js
  pages/partners.js
  pages/wi/counselor-selection-process.js
  pages/wi/partner/[slug].js
  pages/wi/partners.js
  public/svgs/THATConference-white.svg
  styles/baseTheme.js
  utilities/constants.js
  utilities/svgs.js
Labels: ready for review

#361 adds new session status, and fixes key
  components/HomePage/SponsorHighlight.js
  utilities/constants.js
Labels: bug

#362 filters out nulls
  pages/partner/[slug].js
Labels: bug

#376 change April 17 hard coded; to 13
  components/CounselorSelectionProcess/TheProcess.js
  markdown/blog/WI-2020-call-for-counselors-open.md
  pages/member/my-sessions.js
Labels: bug

#382 package bumps
  lib/initApollo.js
  package-lock.json
  package.json
Labels: enhancement

#383 disabling prefetch
  components/HomePage/SponsorHighlight.js
  components/shared/LinkButton.js
  components/shared/ThatLink.js
  pages/partners.js
  pages/wi/counselor-selection-process.js
  pages/wi/index.js
  pages/wi/partners.js
Labels: bug

#368 General FAQ - Corrected a few grammatical and typing oopsies.
  markdown/faq.md
Labels: wip

#392 updates build to handle seo files better
  .gitignore
  package.json
  pages/sitemap.xml.js
  sitemap/pages.json
Labels: bug

#396 Add specific deploy regions for Zeit
  now.json
Labels: enhancement
