Repository ThatConference/that-website, pull requests merged in 2020-07, with the labels that each got.

#555 Update api calls for sessions changes with that-sessions-api pr#65
  components/Member/MySessions/Current.js
  components/Member/SessionEdit/Details.js
  components/Session/Submit/AdditionalInfo.js
  components/Session/Submit/Details.js
  components/Session/Submit/Intro.js
  components/Session/Submit/Lastly.js
  components/shared/SessionPreview.js
  utilities/constants.js
Labels: Critical, enhancement

#559 Shared component: YouTube add story, spec, and refactor to folder
  components/OneDay/Hero.js
  components/RootHomePage/Keynotes.js
  components/shared/YouTubeVideo/YouTubeVideo.js
  components/shared/YouTubeVideo/YouTubeVideo.spec.js
  components/shared/YouTubeVideo/YouTubeVideo.stories.js
  pages/wi/2021/tickets.js
Labels: ready for review

#560 clean up and remove duplication from PR template
  pull_request_template.md
Labels: ready for review

#562 fix member social links
  pages/member/[memberSlug].js
Labels: bug

#566 Rewording of public profile checkbox
  components/Member/Profile/Bio.js
Labels: enhancement

#570 fix partner link. update contributors
  .all-contributorsrc
  README.md
  components/PartnerDetail/HeroSection.js
  pages/partner/[slug].js
Labels: bug
