Repository ThatConference/that-website, pull requests merged in 2020-10, with the labels that each got.

#596 Update communities query for new graph path
  components/RootHomePage/Events.js
Labels: enhancement

#597 add changed parameter 'findBy'
  components/RootHomePage/Events.js
Labels: bug

#599 Refactored event graphql query calls
  components/EventHomePage/SponsorHighlight.js
  components/EventPages/OneDayEvent.js
  components/Header/default.js
  pages/[markdown].js
  pages/wi/2021/[markdown].js
  pages/wi/2021/call-for-counselors.js
  pages/wi/2021/important-dates.js
  pages/wi/2021/index.js
  pages/wi/2021/jobs.js
  pages/wi/2021/partners.js
  pages/wi/2021/plan-your-trip.js
Labels: enhancement

#601 Update graph queries for that-api-partners changes
  .node-version
  pages/partner/[slug].js
  pages/partner/[slug]/job/[jobSlug].js
  pages/partner/[slug]/jobs.js
  pages/wi/2020/jobs.js
Labels: dependencies, enhancement

#602 regression. missed data path from events schema update
  pages/wi/2021/partners.js
Labels: bug

#605 add placeholder image constant; add to partner detail
  components/PartnerDetail/MainLogoSection.js
  components/shared/RoundImage.js
  pages/member/[memberSlug].js
  utilities/constants.js
Labels: ready for review

#603 update wording on isOver13 profile check
  components/Member/Profile/ContactInfo.js
Labels: ready for review

#604 add search to partners page
  components/shared/StandardStyles.js
  pages/partners.js
  styles/globalStyle.js
Labels: ready for review

#606 add apply now link to job page when exists
  components/shared/SocialLinks.js
  pages/partner/[slug]/job/[jobSlug].js
Labels: ready for review

#607 use named exports for lodash
  components/CounselorStart/Header.js
  components/Header/MemberNav.js
  components/Header/MessageBar.js
  components/Header/SecondaryMemberNav.js
  components/Member/MySessions/Current.js
  components/Member/SessionEdit/Details.js
  components/OneDay/Partners.js
  components/PartnerDetail/MainLogoSection.js
  components/RootHomePage/Events.js
  components/layouts/Default.js
  components/layouts/Root.js
  components/shared/LinksInput.js
  components/shared/StringsInput.js
  components/shared/Timeline.js
  pages/member/create.js
  pages/member/edit.js
  pages/member/session-edit/[sessionId].js
  pages/member/session-preview/[sessionId].js
  pages/members.js
  pages/partner/[slug].js
  pages/partner/[slug]/jobs.js
  pages/wi/2020/jobs.js
  pages/wi/2021/counselor-agreement.js
  pages/wi/2021/important-dates.js
  pages/wi/2021/jobs.js
  pages/wi/2021/session/create.js
  pages/wi/2021/voting.js
  pages/wi/2021/voting/review.js
  pages/wi/2021/voting/vote.js
Labels: ready for review
