Repository ThatConference/that-website, pull requests merged in 2020-06, with the labels that each got.

#494 replace img tag with imgix component
  components/shared/RoundImage.js
Labels: enhancement

#499 Update member slug for new api slug scalar
  components/Member/Profile/ContactInfo.js
Labels: bug, enhancement

#498 Brettski/root landing tweak socials
  utilities/constants.js
Labels: enhancement

#506 Add blog post excerpt to post and contributors
  CONTRIBUTING.MD
  markdown/blog/refactoring-THAT-conference-2020.md
Labels: enhancement

#504 Potential fix for 450 No Header on No Partner
  components/PartnerDetail/HeroSection.js
  pages/partner/[slug].js
Labels: ready for review

#527 adding coming soon image for texas
  components/EventPages/ComingSoon.js
  public/images/TX-ComingSoon.jpg
Labels: bug

#530 change patron ticket name
  pages/wi/2020/index.js
Labels: enhancement

#531 correct redirect in member create. Search and fix other /wi issues
  components/Member/Profile/ContactInfo.js
  components/Session/Voting/Shared/NavLinks.js
  pages/member/create.js
  pages/partner/[slug].js
Labels: bug

#536 add support for root md pages update links to non-event pages
  README.md
  components/Footer/index.js
  components/Member/Profile/ContactInfo.js
  components/OneDay/Tickets.js
  markdown/attendee-handbook.md
  pages/[markdown].js
  pages/wi/2020/index.js
  public/images/tickets/2020/patron.png
  public/images/tickets/2020/patroncamper.png
Labels: enhancement

#541 fix social object structure for use with SocialLinks.js
  components/shared/PartnerLogoWithInfo.js
Labels: bug

#547 Updates for accessibility, SEO and performance
  components/Member/Profile/OnlinePresence.js
  components/OneDay/Hero.js
  components/OneDay/Tickets.js
  components/RootHomePage/Hero.js
  components/RootHomePage/Keynotes.js
  components/shared/HeroContainer.js
  components/shared/LinkButton.js
  components/shared/MerchHighlight.js
  components/shared/NewsletterSignupForm.js
  components/shared/ProfileItem.js
  components/shared/RoundImage.js
  components/shared/SocialLinks.js
  components/shared/SquareButton.js
  markdown/wi/2021/attendee-handbook.md
  pages/member/[memberSlug].js
  pages/wi/2021/index.js
  pages/wi/2021/plan-your-trip.js
  public/images/events_meetups_gatherings.jpg
  public/images/landing_hero.jpg
  public/images/logo.that.tx.png
  public/images/logo.that.wi.png
  public/images/open-space-circle.jpg
  public/images/person-placeholder.jpg
Labels: ready for review

#551 Add storybook as well as story, spec and refactoring for LinkButton
  .storybook/main.js
  .storybook/preview.js
  CONTRIBUTING.MD
  components/CallForCounselors/Header.js
  components/CallForCounselors/Process.js
  components/CallForCounselors/TalkIdeas.js
  components/CounselorSelectionProcess/Bottom.js
  components/CounselorStart/Header.js
  components/EventHomePage/Hero.js
  components/EventHomePage/LearnMore.js
  components/EventHomePage/MeetCampers.js
  components/EventHomePage/SpeakerHighlight.js
  components/EventHomePage/SponsorHighlight.js
  components/Header/default.js
  components/OneDay/Hero.js
  components/OneDay/Tickets.js
  components/PartnerDetail/HeroSection.js
  components/RootHomePage/Community.js
  components/RootHomePage/Events.js
  components/RootHomePage/Keynotes.js
  components/RootHomePage/SignUp.js
  components/shared/LinkButton/LinkButton.js
  components/shared/LinkButton/LinkButton.spec.js
  components/shared/LinkButton/LinkButton.stories.js
  components/shared/MerchHighlight.js
  components/shared/SessionHighlight.js
  components/shared/Timeline.js
  components/shared/TitledContentBlock.js
  package-lock.json
  package.json
  pages/contact.js
  pages/partner/[slug].js
  pages/partner/[slug]/job/[jobSlug].js
  pages/partner/[slug]/jobs.js
  pages/partners.js
  pages/wi/2021/become-a-partner.js
  pages/wi/2021/jobs.js
  pages/wi/2021/partners.js
  pages/wi/2021/plan-your-trip.js
  pages/wi/2021/tickets.js
  pages/wi/2021/voting.js
  utilities/index.js
  utilities/themeColorNames.js
Labels: ready for review

#549 add pull request template
  pull_request_template.md
Labels: ready for review
