Repository ThatConference/that-website, pull requests merged in 2020-01, with the labels that each got.

#192 updating hardcoded dates
  components/CallForCounselors/Header.js
  components/Header/MessageBar.js
Labels: bug

#119 fixes social svgs
  components/shared/Icon.js
  components/shared/SocialLinks.js
  utilities/svgs.js
Labels: wip

#197 adds image lazy loading
  components/HomePage/Hero.js
  components/HomePage/LearnMore.js
  components/HomePage/NewsletterSignup.js
  components/HomePage/SponsorHighlight.js
  components/HomePage/Testimonials.js
  components/HomePage/Timeline.js
  components/shared/RoundImage.js
  pages/wi/index.js
  pages/wi/partners.js
Labels: enhancement

#207 Fix typo
  components/CallForCounselors/Perks.js
Labels: bug

#202 Edited copy for consistency with the rest of the page.
  components/CallForCounselors/Header.js
Labels: enhancement

#215 Adds the Counselor's Session Submissions FAQ to the site
  markdown/counselor-submission-faq.md
Labels: enhancement

#220 routing updates
  components/Header/MessageBar.js
  pages/member/[memberSlug].js
  pages/member/create.js
Labels: bug

#255 pre-integration swap to hook and context for hooks
  components/Page.js
  components/User.js
  components/with-auth.js
  hooks/requireAuth.js
  hooks/user.js
  lib/auth0.js
  lib/user.js
  now.json
  package-lock.json
  package.json
  pages/_app.js
  pages/api/me.js
  pages/authTest-hook.js
  pages/authTest-required.js
  pages/authTest-ssr.js
  pages/authTest.js
Labels: enhancement

#265 Merge pull request #264 from ThatConference/sg/session-state
  components/Member/MySessions/Current.js
  components/Member/Profile/Bio.js
  components/Member/Profile/Image.js
  components/Member/Profile/OnlinePresence.js
  components/Member/SessionEdit/Details.js
  components/Session/Submit/Preview.js
  components/shared/Title.js
  components/with-auth.js
  hooks/user.js
  pages/_app.js
  pages/api/me.js
  pages/authTest-hook.js
  pages/authTest-required.js
  pages/authTest-ssr.js
  pages/member/my-sessions.js
  pages/member/session-edit/[sessionId].js
Labels: bug

#270 updates dynamic settings based on window
  lib/auth0-config.js
  lib/auth0.js
Labels: bug

#209 Update Counselor Commitments to more honest about attendance
  components/CounselorAgreement/Commitments.js
Labels: enhancement

#272 adds audience back
  lib/auth0-config.js
Labels: blocker, bug

#283 Sg/getting er done
  components/Member/Profile/Image.js
  components/Member/SessionEdit/Details.js
  components/Member/SessionEdit/Header.js
  components/Session/Submit/AdditionalInfo.js
  components/Session/Submit/Details.js
  components/Session/Submit/Intro.js
  components/Session/Submit/Lastly.js
  components/Session/Submit/Preview.js
  components/shared/FormLayout.js
  components/shared/SquareButton.js
  pages/member/create.js
  pages/member/edit.js
  pages/member/session-edit/[sessionId].js
  pages/wi/session/create.js
  utilities/constants.js
Labels: bug

#296 removes the link to the merch.. new one coming soon
  components/Header/Nav.js
Labels: bug

#309 using tokenCache to get current or refreshed token
  lib/withApolloClient.js
  pages/api/me.js
Labels: bug

#306 add WI 2020 call for counselors newsletter as blog
  CONTRIBUTING.MD
  markdown/blog/WI-2020-call-for-counselors-open.md
  pages/blog.js
  pages/blog/[post].js
  public/images/blog/clark-2019-stage-pointing.jpg
Labels: ready for review
