Repository ThatConference/that-website, pull requests merged in 2020-12, with the labels that each got.

#614 year-end newsletter
  components/RootHomePage/Blog.js
  markdown/blog/that-year-a-retrospective.md
  pages/blog.js
Labels: enhancement

#615 enables that.us redirection
  pages/thatus/[year].js
Labels: Critical, bug

#617 fixes #616 - returning from getInitalProps
  components/shared/Redirect.js
Labels: bug

#618 fixes #616 again - returning from getInitalProps
  components/shared/Redirect.js
Labels: bug

#619 refactor WhatToExpect for Storybook
  components/shared/WhatToExpect/WhatToExpect.js
  components/shared/WhatToExpect/WhatToExpect.spec.js
  components/shared/WhatToExpect/WhatToExpect.stories.js
  package.json
  pages/wi/2021/become-a-partner.js
  pages/wi/2021/index.js
Labels: ready for review

#609 fix up important dates page
  components/shared/Timeline.js
  pages/wi/2021/important-dates.js
  utilities/utilityFunctions.js
Labels: ready for review
