Repository ThatConference/that-website, pull requests merged in 2020-03, with the labels that each got.

#401 Standardize Header Color
  components/Header/MessageBar.js
Labels: bug

#402 force footer to bottom of short content page
  components/Page.js
Labels: bug

#410 errors, errors, moar errors
  .env.build.sample
  components/Page.js
  lib/initApollo.js
  lib/sentry.js
  lib/withApolloClient.js
  next.config.js
  now.json
  package-lock.json
  package.json
  pages/_app.js
  pages/_error.js
Labels: bug, enhancement

#411 bumped packages
  components/Page.js
  lib/initApollo.js
  lib/sentry.js
  package-lock.json
  package.json
Labels: bug

#415 adds user info to chat
  components/Page.js
Labels: enhancement

#414 fixes uuid deprecation
  lib/initApollo.js
Labels: bug

#416 moves where we set chat
  components/Page.js
Labels: bug

#377 WIP: Feature/session voting
  components/HomePage/Hero.js
  components/Member/Profile/Bio.js
  components/Member/Profile/Image.js
  components/Session/Voting/Shared/Icons.js
  components/Session/Voting/Shared/NavLinks.js
  components/Session/Voting/Shared/SessionContent.js
  components/Session/Voting/Shared/SlimSession.js
  components/Session/Voting/Shared/Stats.js
  components/Session/Voting/Shared/VotingFooter.js
  components/shared/JobListing.js
  components/shared/SavingOverlay.js
  components/shared/StandardStyles.js
  components/shared/WhatToExpect.js
  lib/sentry.js
  package-lock.json
  package.json
  pages/member/create.js
  pages/member/edit.js
  pages/member/my-sessions.js
  pages/member/session-edit/[sessionId].js
  pages/member/session-preview/[sessionId].js
  pages/samples/sample-form.js
  pages/samples/toggle-page.js
  pages/wi/index.js
  pages/wi/session/create.js
  pages/wi/voting.js
  pages/wi/voting/review.js
  pages/wi/voting/vote.js
  styles/globalStyle.js
  utilities/constants.js
  utilities/svgs.js
Labels: wip

#426 Ensures session review thumb icons are not too small to use
  components/Session/Voting/Shared/SlimSession.js
Labels: bug

#428 Member Image Filtering on Types for Issue #421
  components/Member/Profile/Image.js
Labels: bug

#433 fix widths to prevent persistent horizontal scrolling
  components/Footer/PageFooter.js
  components/Header/MessageBar.js
  components/Header/index.js
  components/Page.js
  components/shared/ContentSection.js
  pages/wi/index.js
Labels: bug

#455 rollback for PR443. Fixing Horizontal scroll broke logo
  components/Footer/PageFooter.js
  components/Header/MessageBar.js
  components/Header/index.js
  components/Page.js
  components/shared/ContentSection.js
  pages/wi/index.js
Labels: bug

#458 rolled back styled componets
  now.json
  package-lock.json
  package.json
Labels: bug

#462 modified member to allow public and private view
  pages/member/[memberSlug].js
Labels: enhancement

#460 added voting end date to voting info page
  pages/wi/voting.js
  utilities/dates/wi-dates.js
Labels: enhancement

#464 changes the duration of the voting animation
  components/shared/SavingOverlay.js
Labels: enhancement
